name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
main = "src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "pz-solutions.pl"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.pz-solutions.pl", custom_domain = true },
#   { pattern = "quay.pz-solutions.pl", custom_domain = true },
#   { pattern = "gcr.pz-solutions.pl", custom_domain = true },
#   { pattern = "k8s-gcr.pz-solutions.pl", custom_domain = true },
#   { pattern = "k8s.pz-solutions.pl", custom_domain = true },
#   { pattern = "ghcr.pz-solutions.pl", custom_domain = true },
#   { pattern = "cloudsmith.pz-solutions.pl", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.pz-solutions.pl", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
